=== ServiceCutter/ServiceCutter/Samples/JSONSchema_2_user_representations.json
{
  "$schema": "http://json-schema.org/draft-03/schema#",
  "type": "object",
  "properties": {
    "aggregates": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "nanoentities": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    },
    "entities": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "nanoentities": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    },
    "useCases": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "nanoentitiesRead": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "nanoentitiesWritten": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "latencyCritical": {
            "type": "boolean",
            "required": false
          }
        }
      }
    },
    "separatedSecurityZones": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "nanoentities": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    },
    "predefinedServices": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "nanoentities": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    },
    "securityAccessGroups": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "nanoentities": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    },
    "compatibilities": {
      "type": "object",
      "properties": {
        "storageSimilarity": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "characteristic": {
                "type": "string"
              },
              "nanoentities": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            }
          }
        },
        "structuralVolatility": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "characteristic": {
                "type": "string"
              },
              "nanoentities": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            }
          }
        },
        "consistencyCriticality": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "characteristic": {
                "type": "string"
              },
              "nanoentities": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            }
          }
        },
        "securityCriticality": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "characteristic": {
                "type": "string"
              },
              "nanoentities": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            }
          }
        },
        "availabilityCriticality": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "characteristic": {
                "type": "string"
              },
              "nanoentities": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            }
          }
        },
        "contentVolatility": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "characteristic": {
                "type": "string"
              },
              "nanoentities": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "sharedOwnerGroups": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "nanoentities": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    }
  }
}

=== ServiceCutter/ServiceCutter/Engine/src/test/resources/booking_2_user_representations.json
{ 
"useCases": 
	[
		{	
			"name":"createCustomer",
			"nanoentitiesRead": [],
			"nanoentitiesWritten":["Customer.firstname","Customer.name","Customer.street","Customer.city","Customer.creditCard","Customer.accountNr", "Customer.customerIdentifier"]
		},
		{	
			"name":"createBooking",
			"nanoentitiesRead": ["Article.price"],
			"nanoentitiesWritten":["Booking.bookingDate","Booking.paymentDate","Booking.totalPrice","Booking.bookingState","Booking.bookingIdentifier"]
		},
		{	"name":"createArticle",
			"nanoentitiesRead": [],
			"nanoentitiesWritten":["Article.articleName", "Article.price", "Article.serial", "Article.articleIdentifier"]
		},
		{	
			"name":"searchArticles",
			"nanoentitiesRead": ["Article.articleName", "Article.price", "Article.serial"],
			"nanoentitiesWritten":[],
			"isLatencyCritical":"true"
		},
		{	
			"name":"payBooking",
			"nanoentitiesRead": ["Customer.creditCard", "Customer.customerIdentifier", "Article.articleIdentifier"],
			"nanoentitiesWritten":["Booking.paymentDate", "Booking.bookingState"],
			"isLatencyCritical":"true"
		}
	],
"compatibilities": 
	{
		"availabilityCriticality": 
			[
				{
					"characteristic":"Low",
					"nanoentities":[
						"Customer.firstname"
					]
				},
				{
					"characteristic":"Critical",
					"nanoentities":[
						  "Article.articleIdentifier",
						  "Article.articleName",
						  "Article.price",
						  "Article.serial",
						  "Customer.creditCard"
					]
				}
			]
	},
"aggregates":[
  {
	"name": "BookingAggregate",
	"nanoentities":[
        "Booking.bookingDate",
        "Booking.paymentDate",
        "Booking.totalPrice",
        "Booking.bookingState",
		"Booking.bookingIdentifier"
	]
  }
],
"securityAccessGroups":[
  {
	"name": "adminAccess",
	"nanoentities": [
		"Article.articleName",
		"Article.price",
		"Article.serial",
		"Article.articleIdentifier"
	]
  },
  {
	"name": "userAccess",
	"nanoentities":[
		"Customer.firstname",
		"Customer.name",
		"Customer.street",
		"Customer.city",
		"Customer.creditCard",
		"Customer.accountNr",
		"Customer.customerIdentifier"
	]
  }
],
"predefinedServices":[
  {
	"name": "CRM",
	"nanoentities":[
		"Customer.firstname",
		"Customer.name",
		"Customer.street",
		"Customer.city",
		"Customer.creditCard",
		"Customer.accountNr",
		"Customer.customerIdentifier"
	]
  }
]
}
